### PR TITLE
Use an AssemblyLoadContext when building scripts

### LINKED ISSUE #40: Use AssemblyLoadContext to load the generated Assembly
In PDN 4.3, effect plugins are now loaded into separate `AssemblyLoadContext`s which has a few benefits.

First, it means dependencies can be "plugin local" -- two plugins can have a dependency with the same file name but different versions (or they could just be entirely different and accidentally have the same name), and as long as the plugins are in separate directories it will work out because they only load and use types from their own local dependency.

Second, `AssemblyLoadContext`s are _collectible_. This means they can be unloaded and garbage collected! In PDN, I use this to unload an ALC if the DLL I loaded into it winds up having zero plugins in it -- this happens when trying to gather effects from a shared library, for instance, which obviously won't have effects in it. Also happens if none of the plugins _could_ be loaded, like if they were blocked or threw exceptions in their constructors.

Since CodeLab is constantly loading newly compiled generated assemblies, this could be a very good thing.

You don't need to use the `ALC.Unload()` method, as they'll be GC'd automatically as long as you're no longer holding onto the ALC. Basically you just hold onto a tuple of `(AssemblyLoadContext, Assembly)` instead of just `Assembly` and it'll happen automatically (non-deterministically, of course). In fact, I don't recommend calling `Unload()` as it can then get out-of-order with finalizing instances of types that were in the assembly (not a good thing).

You do need to implement a derived class from `ALC`, but thankfully it's simple. In the PDN source, it's `./PaintDotNet/AppModel/PluginAssemblyLoadContext.cs`. And then instead of `Assembly.Load*()` you use `AssemblyLoadContext.Load*()`. You then use the `Assembly` as you normally would.

If you use `Assembly.Load()` then it will load into the default load context, which you don't want for something like CodeLab.

I'm happy to help out with this, and it should be a simple change from what I saw in `ScriptBuilder.cs`

### PR DESCRIPTION
**Pull request by rickbrew**
I haven't been able to test this because the nuget package DLLs aren't copying themselves to the bin directory, so the post-build events fail. So this is untested. It does build, the post-build events just fail and I can't load the plugin in Paint.NET.

But, this is pretty much what you want to do.

Fixes #40

### CODE REVIEW

**Comment by rickbrew** [comment]
Alright, should be good to go

**Comment by toehead2001** [comment]
Is the `ScriptAssemblyLoadContext` class still necessary? Looks like all it does is change the default value of isCollectable to true (in comparison to the base class).

**Comment by rickbrew** [comment]
Oh, I guess not -- I thought `AssemblyLoadClass` was `abstract` but apparently not https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=net-5.0

**Comment by rickbrew** [comment]
Fixed

**Pull request merged**
