### PR TITLE
Update the clipboard template for Paint.NET 4.1.7

### PR DESCRIPTION
**Pull request by 0xC0000054**
Also fixed an issue with the clipboard surface not being disposed.

### CODE REVIEW

**Comment by toehead2001** [comment]
It's probably a good time to rename `img` and `_img` to something more meaningful.

**Comment by 0xC0000054** [comment]
> It's probably a good time to rename `img` and `_img` to something more meaningful.

Good idea.
The template can be further simplified by removing the img property and moving the clipboard reading code into `PreRender`.

**Comment by BoltBait** [comment]
I just came here to refresh my local copy to start on this change.  Thanks for saving me the trouble!

Is this ready to be merged?  Looks like it. But, I don't want to presume.

**Comment by 0xC0000054** [comment]
> Is this ready to be merged? Looks like it. But, I don't want to presume.

It is.

**Pull request merged**
