### PR TITLE
Add options to start with flags

### PR DESCRIPTION
**Pull request by toehead2001**
How's this look?

### CODE REVIEW

**Comment by toehead2001** [comment]
Hmm, hold on, it seems the PluginSupportInfo attribute needs to be on each of these derived classes.

**Comment by BoltBait** [comment]
I think we should just pick one of the single threaded options...

Single Threaded
Single Render Call  <-  I'm leaning toward this one.

Then, let's put an option on the build screen for it so that plugin authors can have it for their plugins.

**Comment by toehead2001** [comment]
Ok, I've removed "Single Threaded", so there's no longer a menu item for that one.
Should be good to go, right?

In a separate commit, I also added "Single Render Call" to the Build DLL form.  fb1339b

**Comment by BoltBait** [comment]
Sounds good.

**Pull request merged**
